### PR TITLE
[fix] unexpected token in OG images

### LINKED ISSUE #1: Unexpected token in OG image
### Description

The generated OG images has unexpected token ` ' `

## Probable Error

```js
${
  data.contributors !== null &&
  data.contributors.map(
    (username, index) => `
    <div key="${index}" class="p-1">
    <img
      src="http://github.com/${username}.png"
      class="rounded-circle text-center"
      alt="${username}"
      style="width: 40px"
    />
    </div>
    `
  )
}
```

## Related Files

https://github.com/codinasion/codinasion-og/blob/6c623e7afec9b09ac44534b85ac3b59d5c18ebd6/pages/api/_components/template/programme.js#L98-L112

https://github.com/codinasion/codinasion-og/blob/6c623e7afec9b09ac44534b85ac3b59d5c18ebd6/pages/api/_components/template/dsa.js#L89-L103

https://github.com/codinasion/codinasion-og/blob/6c623e7afec9b09ac44534b85ac3b59d5c18ebd6/pages/api/_components/template/home.js#L81-L112

### Screenshots

Unexpected Tokens

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by smdpro**
### Why:
the map functions were updated
Closes #1

### What's being changed:
dsa.js
home.js
programme.js
### Check off the following:

- [ x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @smdpro 

Thanks for opening this PR

This PR will be reviewed and merged shortly 👍🏻

File: pages/api/_components/template/programme.js [hunk 1]
```diff
@@ -123,20 +121,18 @@ export default async function getProgrammeHtml(data) {
...
-        `
-          )
+              }.png`}
+                class='rounded-circle text-center'
+                alt='image'
+                style='width: 40px; max-height: 40px'
+              />
+            </div>
+          ))
         }
```
Comment (harshraj8843) [inline pages/api/_components/template/programme.js]: Hey @smdpro 

Sorry, but this will not fix the issue

### Reason

- `getProgrammeHtml` return html as string, but the updated code will return `string` + `component` + `string`. It should be all string

Error !!!

**Review by harshraj8843 — CHANGES_REQUESTED** [review]

File: pages/api/_components/template/programme.js (hunk 1 above)
Comment (smdpro) [reply pages/api/_components/template/programme.js]: Hi @harshraj8843
I checked it locally, and fetching data has not returned JSON format. 
for route :
**http://localhost:3000/api?url=https://codinasion.vercel.app/programme/add-two-numbers**
console output :
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/smd/codes/openSource/codinasion-og/.env
FetchError: invalid json response body at https://raw.githubusercontent.com/codinasion/codinasion-data/master/data/contributors.json reason: Unexpected token : in JSON at position 3
    at /home/smd/codes/openSource/codinasion-og/node_modules/next/dist/compiled/node-fetch/index.js:1:49606
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async handler (/home/smd/codes/openSource/codinasion-og/.next/server/pages/api.js:573:30)
    at async Object.apiResolver (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/api-utils/node.js:185:9)
    at async NextNodeServer.runApi (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/next-server.js:395:9)
    at async Object.fn (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/base-server.js:496:37)
    at async Router.execute (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/router.js:226:36)
    at async NextNodeServer.run (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/base-server.js:606:29)
    at async NextNodeServer.handleRequest (/home/smd/codes/openSource/codinasion-og/node_modules/next/dist/server/base-server.js:321:20) {
  type: 'invalid-json'
}
There is something wrong with calling API
call  [ https://raw.githubusercontent.com/codinasion/codinasion-data/master/data/contributors.json] in your browser. You will get 404: Not Found

Comment (smdpro) [reply pages/api/_components/template/programme.js]: `const contributors = await fetch(
      `https://raw.githubusercontent.com/${"codinasion"}/${"codinasion-data"}/master/data/contributors.json`,
      {
        method: "GET",
        headers: {
          Authorization: `token ${process.env.GITHUB_TOKEN}`,
        },
      }
    ).then((res) => res.json());`

"codinasion" in fetch URL  is not a dynamic variable, just a static string?

Comment (harshraj8843) [reply pages/api/_components/template/programme.js]: > Hi @harshraj8843 I checked it locally, and fetching data has not returned JSON format.

Hey @smdpro, sorry for the late reply.

This issue occurred because `codinasion-data` (the repo from which json data is being fetched) is `private`. So, it can only be accessed by Codinasion members.

[Become a member of codinasion](https://github.com/codinasion/.github/issues/new?assignees=&labels=welcome+%F0%9F%8E%89%F0%9F%8E%89%F0%9F%8E%89&template=invitation.yml&title=Please+invite+me+to+Codinasion)

And please don't forget to add your `personal access token` in `.env` (GITHUB_TOKEN=your_personal_access_token)

> "codinasion" in fetch URL is not a dynamic variable, just a static string?

Yes, but this is intentional for the purpose of review. It will be updated later

**Review by smdpro — COMMENTED** [review]
new update

**Comment by harshraj8843** [comment]
> new update

`.join("")` worked like a charm 🎉 🎉 🎉 

So, as far as i understood

```js
${
  data.contributors !== null &&
  data.contributors
    .map(
      (username, index) => `
  <div key="${index}" class="p-1">
    <img
      src="http://github.com/${username}.png"
      class="rounded-circle text-center"
      alt="${username}"
      style="width: 40px"
    />
  </div>
  `
    )
};
```

is making an array of image strings. That's why there is `,`. But since we are using image width and height property, it seems like ` ' `

So, the final solution is 

```js
${
  data.contributors !== null &&
  data.contributors
    .map(
      (username, index) => `
  <div key="${index}" class="p-1">
    <img
      src="http://github.com/${username}.png"
      class="rounded-circle text-center"
      alt="${username}"
      style="width: 40px"
    />
  </div>
  `
    )
    .join("")
};
```

Thanks very much for the fix 🤗
